server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/trybe
    username: root
    password: 1234

dbc:
  h2:
    mem: speciality_database
    username: speciality-app
    password: speciality-app!

logging:
  file:
    name: ./logs/speciality-app.log